#!/bin/bash
make
fin=./data/t1e4; echo $fin serial; ./serialdf "$fin".txt "$fin"_serial.txt > "$fin"_stdout_serial.txt
fin=./data/t1e5; echo $fin serial; ./serialdf "$fin".txt "$fin"_serial.txt > "$fin"_stdout_serial.txt
fin=./data/t1e6; echo $fin serial; ./serialdf "$fin".txt "$fin"_serial.txt > "$fin"_stdout_serial.txt
fin=./data/t1e7; echo $fin serial; ./serialdf "$fin".txt "$fin"_serial.txt > "$fin"_stdout_serial.txt


for i in 3 5 9 13
do
	echo $i
				fin=./data/t1e4; echo $fin parallel; mpirun -n $i ./paralleldf "$fin".txt "$fin"_"$i"_parallel.txt > "$fin"_stdout_"$i"_parallel.txt
				fin=./data/t1e5; echo $fin parallel; mpirun -n $i ./paralleldf "$fin".txt "$fin"_"$i"_parallel.txt > "$fin"_stdout_"$i"_parallel.txt
				fin=./data/t1e6; echo $fin parallel; mpirun -n $i ./paralleldf "$fin".txt "$fin"_"$i"_parallel.txt > "$fin"_stdout_"$i"_parallel.txt
				fin=./data/t1e7; echo $fin parallel; mpirun -n $i ./paralleldf "$fin".txt "$fin"_"$i"_parallel.txt > "$fin"_stdout_"$i"_parallel.txt
done
